name: Sync Sitemap
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Fetch Sitemap from Worker
        run: curl https://classicforum.indiachan.workers.dev/sitemap.xml -o sitemap.xml

      - name: Commit and Push
        run: |
          git config --global user.name "Sitemap-Bot"
          git config --global user.email "bot@indiachan.com"
          git add sitemap.xml
          git commit -m "Update sitemap from Worker" || exit 0
          git push
